### ISSUE TITLE
Connected but no internet

### ISSUE THREAD

**Issue by shoaib039** [OpenVPN/as-docker#14]
I have configured everything very well and also changed Server IP Address. Create user and download .ovpn profile to my phone. VPN also connected successfully, just no internet. Help me what to do and what to fix.

My Docker IP Address: **172.21.0.2**
Server IP Address: **140.238.225.44**

![image](https://github.com/user-attachments/assets/7573796f-a465-4917-88fe-4f67727e9241)

![image](https://github.com/user-attachments/assets/14efddf2-5d12-4faf-b91e-1cdfd7e03b1e)

![image](https://github.com/user-attachments/assets/023e37be-1f74-486f-8a25-421f337d11bc)

![Image_20241014202435](https://github.com/user-attachments/assets/5ea5e3e3-8249-44c9-bf61-23301061f145)

**Comment by uddr** [comment]
@shoaib039 assuming this is Oracle cloud you may check if you have proper IG/NAT configuration and open ports in the cloud and OS firewalls.

**Comment by novaflash** [comment]
A common problem is that by default Access Server pushes its DNS servers to the VPN client, and if these are DNS servers that either don't respond to VPN clients or are unroutable, you lose Internet access. So go to VPN Settings and try turning off pushing of DNS server, or push actually valid DNS servers.

**Comment by shoaib039** [comment]
> A common problem is that by default Access Server pushes its DNS servers to the VPN client, and if these are DNS servers that either don't respond to VPN clients or are unroutable, you seemingly lose Internet access. So go to VPN Settings and try turning off pushing of DNS servers or pushing actually valid DNS servers.

Thank you so much. Actually, before, I had forgotten to add DNS. Now I have added Google DNS. Now I have internet; its working well now.

![image](https://github.com/user-attachments/assets/56a89805-3688-4ec6-8d60-7a9901212ebe)

![image](https://github.com/user-attachments/assets/4c330ac5-bef7-47b5-b5db-86d499410bfd)
