### ISSUE TITLE
Update the image on docker hub

### ISSUE THREAD

**Issue by DSchroer** [OpenVPN/as-docker#6]
Hello. The docker hub image is 2 months old with some new changes in the repo that are not synced. Can someone update it please?

**Comment by uddr** [comment]
Hello @DSchroer,

Thanks for the request.
We are planning the new Access Server release soon.
So the updated Docker image is coming with the new AS version.

Also JFYI, the `Dockerfile` and `docker-build.sh` for AS are opensource and anyone should be able to build updated image anytime.

**Comment by uddr** [comment]
hello @DSchroer 
the new AS docker image with `2.14.0-b90cb316-Ubuntu22` and `latest` tags was pushed today
